(add-to-list 'load-path "~/.emacs.d/elisp/")

;; packages in elips dir
(load-library "melpa")
(load-library "clojure")

;; code generated by melpa during package installation
;; keeping in .gitignore, as well as the proper installed packages
(add-to-list 'load-path "~/.emacs.d/melpa-gen/")

;; packages in melpa-gen dir
(load-library "cider")
